//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_imEntities : DbContext
    {
        public db_imEntities()
            : base("name=db_imEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fact_areas> fact_areas { get; set; }
        public virtual DbSet<fact_bancos> fact_bancos { get; set; }
        public virtual DbSet<fact_departamentos> fact_departamentos { get; set; }
        public virtual DbSet<fact_especialidad_escolar> fact_especialidad_escolar { get; set; }
        public virtual DbSet<fact_estados> fact_estados { get; set; }
        public virtual DbSet<fact_estatus> fact_estatus { get; set; }
        public virtual DbSet<fact_generos> fact_generos { get; set; }
        public virtual DbSet<fact_lenguajes> fact_lenguajes { get; set; }
        public virtual DbSet<fact_licencias> fact_licencias { get; set; }
        public virtual DbSet<fact_marcas> fact_marcas { get; set; }
        public virtual DbSet<fact_municipios> fact_municipios { get; set; }
        public virtual DbSet<fact_nivel_escolar> fact_nivel_escolar { get; set; }
        public virtual DbSet<fact_nivel_lenguaje> fact_nivel_lenguaje { get; set; }
        public virtual DbSet<fact_paises> fact_paises { get; set; }
        public virtual DbSet<fact_secciones> fact_secciones { get; set; }
        public virtual DbSet<fact_tipo_escolar> fact_tipo_escolar { get; set; }
        public virtual DbSet<fact_tipo_rfc> fact_tipo_rfc { get; set; }
        public virtual DbSet<fact_tipo_usuarios> fact_tipo_usuarios { get; set; }
        public virtual DbSet<inf_bancarios> inf_bancarios { get; set; }
        public virtual DbSet<inf_centros> inf_centros { get; set; }
        public virtual DbSet<inf_centros_dep> inf_centros_dep { get; set; }
        public virtual DbSet<inf_clientes> inf_clientes { get; set; }
        public virtual DbSet<inf_contacto> inf_contacto { get; set; }
        public virtual DbSet<inf_contribuyentes> inf_contribuyentes { get; set; }
        public virtual DbSet<inf_escolares> inf_escolares { get; set; }
        public virtual DbSet<inf_fiscales> inf_fiscales { get; set; }
        public virtual DbSet<inf_productos> inf_productos { get; set; }
        public virtual DbSet<inf_proveedor> inf_proveedor { get; set; }
        public virtual DbSet<inf_usuarios> inf_usuarios { get; set; }
        public virtual DbSet<fact_grado_escolar> fact_grado_escolar { get; set; }
        public virtual DbSet<inf_productos_dep> inf_productos_dep { get; set; }
    }
}
