//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fact_especialidad_escolar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fact_especialidad_escolar()
        {
            this.inf_escolares = new HashSet<inf_escolares>();
        }
    
        public int id_especialidad_escolar { get; set; }
        public string desc_especialidad_escolar { get; set; }
        public int id_tipo_escolar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_escolares> inf_escolares { get; set; }
        public virtual fact_tipo_escolar fact_tipo_escolar { get; set; }
    }
}
