//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fact_grado_escolar
    {
        public Nullable<int> id_grado_escolar { get; set; }
        public string desc_grado_escolar { get; set; }
        public int id_tipo_escolar { get; set; }
    
        public virtual fact_tipo_escolar fact_tipo_escolar { get; set; }
    }
}
