//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fact_tipo_escolar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fact_tipo_escolar()
        {
            this.fact_especialidad_escolar = new HashSet<fact_especialidad_escolar>();
        }
    
        public int id_tipo_escolar { get; set; }
        public string desc_tipo_escolar { get; set; }
        public int id_nivel_escolar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fact_especialidad_escolar> fact_especialidad_escolar { get; set; }
        public virtual fact_nivel_escolar fact_nivel_escolar { get; set; }
        public virtual fact_grado_escolar fact_grado_escolar { get; set; }
    }
}
