//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_bancarios
    {
        public int id_bancario { get; set; }
        public Nullable<int> id_banco { get; set; }
        public string tarjeta { get; set; }
        public string clabe { get; set; }
        public System.Guid id_usuario { get; set; }
    
        public virtual fact_bancos fact_bancos { get; set; }
        public virtual inf_usuarios inf_usuarios { get; set; }
    }
}
