//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_productos_dep
    {
        public Nullable<int> id_producto_dep { get; set; }
        public Nullable<int> id_caracteristica { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> cantidad_menor { get; set; }
        public int id_producto { get; set; }
    
        public virtual inf_productos inf_productos { get; set; }
    }
}
