//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_centros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_centros()
        {
            this.inf_centros_dep = new HashSet<inf_centros_dep>();
        }
    
        public System.Guid id_centro { get; set; }
        public string codigo_centro { get; set; }
        public Nullable<int> id_licencia { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_municipio { get; set; }
        public string colonia { get; set; }
        public string calle_num { get; set; }
        public string cp { get; set; }
        public string telefono { get; set; }
        public string telefono_alt { get; set; }
        public string email { get; set; }
        public string email_alt { get; set; }
    
        public virtual fact_estatus fact_estatus { get; set; }
        public virtual fact_licencias fact_licencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_centros_dep> inf_centros_dep { get; set; }
    }
}
