//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_centros_dep
    {
        public int id_centros_dep { get; set; }
        public System.Guid id_centro { get; set; }
        public System.Guid id_usuario { get; set; }
    
        public virtual inf_centros inf_centros { get; set; }
        public virtual inf_usuarios inf_usuarios { get; set; }
    }
}
