//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_fiscales
    {
        public int id_fiscales { get; set; }
        public string razon_social { get; set; }
        public Nullable<int> id_tipo_rfc { get; set; }
        public string rfc { get; set; }
        public Nullable<int> id_municipio { get; set; }
        public string colonia { get; set; }
        public string calle_num { get; set; }
        public string cp { get; set; }
        public string telefono { get; set; }
        public string telefono_alt { get; set; }
        public string email { get; set; }
        public string email_alt { get; set; }
        public System.Guid id_usuario { get; set; }
    
        public virtual fact_municipios fact_municipios { get; set; }
        public virtual fact_tipo_rfc fact_tipo_rfc { get; set; }
    }
}
