//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_productos
    {
        public int id_producto { get; set; }
        public string codigo_producto { get; set; }
        public string desc_producto { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual fact_marcas fact_marcas { get; set; }
        public virtual inf_productos_dep inf_productos_dep { get; set; }
    }
}
