//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_intelimundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_escolares
    {
        public int id_escolar { get; set; }
        public Nullable<int> id_grado_escolar { get; set; }
        public int id_lenguaje { get; set; }
        public int id_nivel_lenguaje { get; set; }
        public int id_especialidad_escolar { get; set; }
        public System.Guid id_usuario { get; set; }
    
        public virtual fact_especialidad_escolar fact_especialidad_escolar { get; set; }
        public virtual fact_lenguajes fact_lenguajes { get; set; }
        public virtual fact_nivel_lenguaje fact_nivel_lenguaje { get; set; }
        public virtual inf_usuarios inf_usuarios { get; set; }
    }
}
